scheme: Pisces

favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/safari-pinned-tab.svg

creative_commons:
  license: by-nc-sa
  size: big
  sidebar: true

menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive


math:
  every_page: false
  mathjax:
    enable: true

pangu: true

local_search:
  enable: true
